# repos:
#   - repo: https://github.com/pre-commit/pre-commit-hooks
#     rev: v4.5.0
#     hooks:
#       - id: check-yaml
#       - id: no-commit-to-branch
#         args: [-b, main, -b, development]
#   - repo: https://github.com/gitguardian/ggshield
#     rev: v1.22.0
#     hooks:
#       - id: ggshield
