export enum QuestionKey {
  RESIDENTIAL_STATUS_RESIDENTIAL_STATUS = 'residential-status/residential-status',
  RESIDENTIAL_STATUS_MOVED_BOROUGH = 'residential-status/moved-borough',
  RESIDENTIAL_STATUS_HOMELESS = 'residential-status/homeless',
  RESIDENTIAL_STATUS_ASBO_BEHAVIOUR = 'residential-status/asbo-behaviour',
  RESIDENTIAL_STATUS_ARMED_FORCES = 'residential-status/armed-forces',
  RESIDENTIAL_STATUS_MOBILITY_SCHEME = 'residential-status/mobility-scheme',
  RESIDENTIAL_STATUS_HOMELESSNESS_ACCEPTED = 'residential-status/homelessness-accepted',
  RESIDENTIAL_STATUS_SOCIAL_HOUSING = 'residential-status/social-housing',
  RESIDENTIAL_STATUS_PROVIDING_CARE = 'residential-status/providing-care',
  RESIDENTIAL_STATUS_DOMESTIC_VIOLENCE = 'residential-status/domestic-violence',
  RESIDENTIAL_STATUS_STUDYING_OUTSIDE_BOROUGH = 'residential-status/studying-outside-borough',
  RESIDENTIAL_STATUS_INSTITUTIONS = 'residential-status/institutions',
  CITIZENSHIP = 'immigration-status/citizenship',
  UK_STUDYING = 'immigration-status/uk-studying',
  IMMIGRATION_VISA = 'immigration-status/work-or-study-visa',
  IMMIGRATION_EA_NATIONAL = 'immigration-status/eea-national',
  IMMIGRATION_SPONSERSHIP = 'immigration-status/receiving-sponsorship',
  IMMIGRATION_STATUS = 'immigration-status/legal-status',
  IMMIGRATION_SETTLED_STATUS = 'immigration-status/settled-status',
}
